# Generated by Django 4.2.5 on 2023-10-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_project_portfolio_alter_student_portfolio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectsInPortfolio',
        ),
    ]
